name: pull_request_from_stage
# makes automated pull request
on:
  push:
    branches:
      - "stage"


jobs:
  set-up-gce:
    runs-on: ubuntu-latest
    steps:

      - name:  Check out files
        uses:  actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
