DROP VIEW IF EXISTS podio.standorte_basisdaten_view;

CREATE VIEW podio.standorte_basisdaten_view AS (

SELECT app_item_id as standort_id,
	created_on,
	last_event_on,
	titel,
	vertrags_id_2,
	ist::json ->> 'text' as aktuell_online,
	(im_kursnet_seit::json ->> 'start_date')::date as in_kursnet_seit,
	kursnet::json ->> 'text' as status,
	zertifizierung_status::json ->> 'text' as zertifizierung_status,
	zertifikat,
	dienstleister::json ->> 'text' as dienstleister,
	zwischen_kt_und,
	mietobjekt_beschreibung,
	(beginn::json ->> 'start_date')::date as beginn,
	befristung::json ->> 'text' as befristung,
	mindestlaufzeit,
	automatische_verlangerung,
	kundigungsfrist,
	bank,
	iban,
	bic,
	kosten_netto,
	kosten_brutto_16,
	kosten_brutto_19,
	kosten_gesamt_16,
	kosten_gesamt,
	kaution::json ->> 'text' as kaution,
	kautionhohe,
	kaution_bar_kautionsburgschaft,
	zahlweise::json ->> 'text' as zahlweise,
	zahl_rhythmus::json ->> 'text' as zahl_rhythmus,
	vertrags_historie_2,
	standort_suffix,
	kursnet_anzeigename,
	email_2,
	telefon_2,
	fax,
	anzahl_schulungsplatze_2,
	grosse_in_qm,
	firmenspezifische_bilder,
	total_current_attandees,
	firmenname,
	adresse_standort,
	state,
	ansprechpartner_anrede ->> 'text' as ansprechpartner_anrede,
	ansprechpartner,
	telefon_dienstleister,
	email_dienstleister,
	web_adresse_diensleister,
	field_2,
	standort_mailing_historie_2,
	offnungszeiten_mo_fr_2,
	offnungszeiten_sa_3,
	offnungszeiten_so_3,
	current_week_attandees_remaining_seats,
	postalcode,
	city,
	street,
	zenturia_nummer_eingetragen_ja_1,
	standortbasisdaten_id,
	has_kursnet_standort,
	onlineafternextupload,
	onlinepotential,
	docaddress,
	docpostaladdress,
	telefon,
	email,
	anzahl_qs_kursnet_standorte,
	anzahl_schulungsplatze,
	kundigung_status,
	anzahl_fachbereiche::json ->> 'text' as anzahl_fachbereiche,
	mitarbeiterzahl_kopfe,
	mitarbeiteranzahl_vza,
	zertifizierungs_nr,
	zahlungs_status::json ->> 'text' as zahlungs_status,
	kosten_brutto,
	nebenkosten,
	dauerrechnung::json ->> 'text' as dauerrechnung,
	gekundigt::json ->> 'text' as gekundigt,
	mitarbeiter_am_standort,
	adresse_diensteister,
	etage,
	hygiene_konzept_vorhanden::json ->> 'text' as hygiene_konzept_vorhanden,
	dq_standort_nummer,
	dqs_nummer_vorhanden::json ->> 'text' as dqs_nummer_vorhanden,
	wettbewerbsschutz_liegt_vor::json ->> 'text' as wettbewerbsschutz_liegt_vor,
	newsletter::json ->> 'text' as newsletter,
	umgezogen::json ->> 'text' as umgezogen,
	internes_audit_durchgefuhrt_2::json ->> 'text' as internes_audit_durchgefuhrt_2,
	(datum_der_prufung_start::json ->> 'start_date')::date as datum_der_prufung_start ,
	prufer,
	teilnehmer_an_standortenstandorte,
	kontaktliste_id,
	calcupdate,
	ffmt_ubersicht_ids,
	laptop_vor_ort_2::json ->> 'text' as laptop_vor_ort_2 ,
	wlan_zugangscodes_2,
	notiz_hinzufugen as notiz_2,
	(letzte_schulung_des_empfanges_3::json ->> 'start_date')::date as letzte_schulung_des_empfanges,
	automatische_mieterhohung,
	(bis::json ->> 'start_date')::date as gemietet_bis,
	gesprachsprotokolle,
	fax_dienstleister,
	kundennummer,
	notizen,
	firmenspezifische_besonderheiten_am_standort,
	alte_adresse,
	video_der_raumlichkeiten,
	covid19_hotspot::json ->> 'text' as covid19_hotspot,
	fur_teilnehmer_zuganglich::json ->> 'text' as fur_teilnehmer_zuganglich,
	info,
	kursnet_informationen_is_set_yes1,
	pad_fachkraft_vor_ort
FROM podio.standorte_standorte_basisdaten
    );

-- SET OWNER
ALTER TABLE podio.standorte_basisdaten_view  OWNER TO read_only;