name: pull_request_from_stage
# makes automated pull request
on:
  push:
    branches:
      - "stage"


jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:

      - name:  Check out files
        uses:  actions/checkout@v3

      - name: Create a Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #pr_label: "feature, automated pr"
          pr_title: ${{ github.event.commits[0].message }}
          pr_assignee: ${{ github.actor }}
