name: pull_request_from_stage
# makes automated pull request
on:
  push:
    branches:
      - "stage"


jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:

      - name:  Check out files
        uses:  actions/checkout@v3

      # - name: Create a Pull Request
      #   uses: repo-sync/pull-request@v2
      #   with:
      #     destination_branch: "master"
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     #pr_label: "feature, automated pr"
      #     pr_title: ${{ github.event.commits[0].message }}
      #     pr_assignee: ${{ github.actor }}

      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            schemas/**/*.sql

      - name: List all added files
        run: |
          for file in ${{ steps.changed-files-specific.outputs.added_files }}; do
            echo "$file was added"
          done
      
      - name: List all modified files
        run: |
          for file in ${{ steps.changed-files-specific.outputs.modified_files }}; do
            echo "$file was modified"
          done

      - name: Set up Cloudsql proxy to DWH
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo 'Changed files detected, starting cloudsql proxy.'